version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
    working_directory: ~/teamspeak-server
    steps:
      - checkout
      - run:
          name: Install AWS CLI and Deploy Cloudformation
          command: |
            sudo apt-get update && sudo apt install python3 -y --force-yes
            sudo apt install python3-pip -y --force-yes
            sudo pip install -q awscli --upgrade
      - run: ./deploy.sh
