version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
    working_directory: ~/teamspeak-server
    steps:
      - checkout
      - run:
          name: Install AWS CLI and Deploy Cloudformation
          command: |
            sudo rm /etc/apt/sources.list
            sudo apt update
            sudo add-apt-repository universe
            echo "deb [trusted=yes] http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "deb-src [trusted=yes] http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "Acquire::Check-Valid-Until false;" | sudo tee -a /etc/apt/apt.conf.d/10-nocheckvalid
            echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | sudo tee -a /etc/apt/preferences.d/10-archive-pin
            sudo apt-get update && sudo apt-get install -qq -y python3-pip libpython-dev
            sudo pip install -q awscli --upgrade
      - run: ./deploy.sh
